name: Python Greetings Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: [self-hosted]
    steps:
      - name: Installing dependencies
        run: echo "Installing deps"
      - name: use checkout@4
        uses: actions/checkout@v4
      - name: Checking out pgreetings
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: p-greetings
      - name: Install Python dependencies
        working-directory: p-greetings
        run: |
          echo "Installing req depps from requirements.txt..."
          pip3 install -r requirements.txt

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: [self-hosted]
    steps:
      - name: Deploying to dev environment
        run: echo "Deploying deps"
      - name: Setup dev
        uses: ./.github/actions/deploy.yaml
        with:
          env: dev
          port: 7001 

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: [self-hosted]
    steps:
      - name: Running tests on dev
        run: echo "Running tests in dev"
      - name: Test dev
        uses: ./.github/actions/test.yaml
        with:
          env: dev
  deploy-to-staging:
    needs: tests-on-dev
    runs-on: [self-hosted]
    steps:
      - name: Deploying to staging
        run: echo "Deploying to stage env"
      - name: Setup staging
        uses: ./.github/actions/deploy.yaml
        with:
          env: staging
          port: 7002

  tests-on-staging:
    needs: deploy-to-staging
    runs-on: [self-hosted]
    steps:
      - name: Running tests on staging
        run: echo "Running tests in stage"
      - name: Test staging
        uses: ./.github/actions/test.yaml
        with:
          env: staging

  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: [self-hosted]
    steps:
      - name: Deploying to pre-production
        run: echo "Deploying to pre-prodd env"
      - name: Setup preprod
        uses: ./.github/actions/deploy.yaml
        with:
          env: preprod
          port: 7003

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: [self-hosted]
    steps:
      - name: Running tests on pre-production
        run: echo "Running tests in pre-prod env"
      - name: Test preprod
        uses: ./.github/actions/test.yaml
        with:
          env: preprod

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: [self-hosted]
    steps:
      - name: Deploying to production
        run: echo "Deploying to prod"
      - name: Setup prod
        uses: ./.github/actions/deploy.yaml
        with:
          env: prod
          port: 7004

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: [self-hosted]
    steps:
      - name: Running tests on production
        run: echo "Running tests in prod"
      - name: Test Prod
        uses: ./.github/actions/test.yaml
        with:
          env: prod
